const { cmd } = require("../command");
const axios = require("axios");
const fs = require("fs");
const config = require("../config");

// Formatted message function
async function sendFormattedMessage(conn, from, text, sender, userName, externalBody = '', bodyText = '') {
    try {
        await conn.sendMessage(from, {
            text: text,
            contextInfo: {
                isForwarded: true,
                title: "ɴᴊᴀʙᴜʟᴏ ᴜɪ",
                body: bodyText || text,
                forwardedNewsletterMessageInfo: {
                    newsletterJid: config.NEWSLETTER,
                    newsletterName: '╭••➤ɴᴊᴀʙᴜʟᴏ ᴜɪ',
                    serverMessageId: 143
                },
                forwardingScore: 999,
                externalAdReply: {
                    title: "ɴᴊᴀʙᴜʟᴏ ᴜɪ",
                    body: externalBody || "AI Image Generator",
                    thumbnailUrl: config.FANAIMG,
                    sourceUrl: config.NJABULOURL,
                    mediaType: 1,
                    renderSmallThumbnail: true
                }
            }
        }, { 
            quoted: {
                key: {
                    fromMe: false,
                    participant: `0@s.whatsapp.net`,
                    remoteJid: "status@broadcast"
                },
                message: {
                    contactMessage: {
                        displayName: userName || "User",
                        vcard: `BEGIN:VCARD\nVERSION:3.0\nN:${userName || "User"};USER;;;\nFN:${userName || "User"}\nitem1.TEL;waid=${sender?.split('@')[0] || '0'}:${sender?.split('@')[0] || '0'}\nitem1.X-ABLabel:User\nEND:VCARD`
                    }
                }
            }
        });
    } catch (err) {
        console.error("Error in sendFormattedMessage:", err);
        await conn.sendMessage(from, { text: text });
    }
}

cmd({
  pattern: "fluxai",
  alias: ["flux", "imagine"],
  react: "🚀",
  desc: "Generate an image using AI.",
  category: "main",
  filename: __filename
}, async (conn, mek, m, { q, reply, sender, pushname, from }) => {
  try {
    if (!q) {
      await sendFormattedMessage(
        conn, 
        from, 
        "🎨 *Please provide a prompt for the image*\n\n📌 *Usage:* .fluxai cute cat\n🔍 *Example:* .fluxai beautiful sunset over mountains", 
        sender, 
        pushname,
        "AI Image - Error",
        "No prompt"
      );
      return;
    }

    await sendFormattedMessage(
      conn, 
      from, 
      `🎨 *Creating your image...*\n\n📝 *Prompt:* ${q}\n⏳ Please wait!`, 
      sender, 
      pushname,
      "AI Image Generator",
      "Generating"
    );

    const apiUrl = `https://api.siputzx.my.id/api/ai/flux?prompt=${encodeURIComponent(q)}`;
    const response = await axios.get(apiUrl, { responseType: "arraybuffer", timeout: 60000 });

    if (!response || !response.data) {
      await sendFormattedMessage(
        conn, 
        from, 
        "❌ *Error generating image*\n\nAPI did not return a valid image. Try again later.", 
        sender, 
        pushname,
        "AI Image - Error",
        "Generation failed"
      );
      return;
    }

    const imageBuffer = Buffer.from(response.data, "binary");

    await conn.sendMessage(from, {
      image: imageBuffer,
      caption: `🎨 *AI Generated Image*\n\n📝 *Prompt:* ${q}\n\n✨ *Generated by Flux AI*`
    }, { quoted: mek });

    await sendFormattedMessage(
      conn, 
      from, 
      `✅ *Image generated successfully!*\n\n📝 *Prompt:* ${q}\n\nEnjoy your AI artwork!`, 
      sender, 
      pushname,
      "AI Image - Success",
      "Image delivered"
    );

  } catch (error) {
    console.error("FluxAI Error:", error);
    await sendFormattedMessage(
      conn, 
      from, 
      `❌ *An error occurred*\n\n${error.message || "Unknown error"}\n\nPlease try again later.`, 
      sender, 
      pushname,
      "AI Image - Error",
      "Generation failed"
    );
  }
});

cmd({
  pattern: "stablediffusion",
  alias: ["sdiffusion", "imagine2", "sd"],
  react: "🚀",
  desc: "Generate an image using Stable Diffusion AI.",
  category: "main",
  filename: __filename
}, async (conn, mek, m, { q, reply, sender, pushname, from }) => {
  try {
    if (!q) {
      await sendFormattedMessage(
        conn, 
        from, 
        "🎨 *Please provide a prompt for the image*\n\n📌 *Usage:* .sdiffusion cute cat\n🔍 *Example:* .sdiffusion cyberpunk city", 
        sender, 
        pushname,
        "AI Image - Error",
        "No prompt"
      );
      return;
    }

    await sendFormattedMessage(
      conn, 
      from, 
      `🎨 *Creating your image with Stable Diffusion...*\n\n📝 *Prompt:* ${q}\n⏳ Please wait!`, 
      sender, 
      pushname,
      "AI Image Generator",
      "Generating"
    );

    const apiUrl = `https://api.siputzx.my.id/api/ai/stable-diffusion?prompt=${encodeURIComponent(q)}`;
    const response = await axios.get(apiUrl, { responseType: "arraybuffer", timeout: 60000 });

    if (!response || !response.data) {
      await sendFormattedMessage(
        conn, 
        from, 
        "❌ *Error generating image*\n\nAPI did not return a valid image. Try again later.", 
        sender, 
        pushname,
        "AI Image - Error",
        "Generation failed"
      );
      return;
    }

    const imageBuffer = Buffer.from(response.data, "binary");

    await conn.sendMessage(from, {
      image: imageBuffer,
      caption: `🎨 *AI Generated Image*\n\n📝 *Prompt:* ${q}\n\n✨ *Generated by Stable Diffusion*`
    }, { quoted: mek });

    await sendFormattedMessage(
      conn, 
      from, 
      `✅ *Image generated successfully!*\n\n📝 *Prompt:* ${q}\n\nEnjoy your AI artwork!`, 
      sender, 
      pushname,
      "AI Image - Success",
      "Image delivered"
    );

  } catch (error) {
    console.error("StableDiffusion Error:", error);
    await sendFormattedMessage(
      conn, 
      from, 
      `❌ *An error occurred*\n\n${error.message || "Unknown error"}\n\nPlease try again later.`, 
      sender, 
      pushname,
      "AI Image - Error",
      "Generation failed"
    );
  }
});

cmd({
  pattern: "stabilityai",
  alias: ["stability", "imagine3", "stableai"],
  react: "🚀",
  desc: "Generate an image using Stability AI.",
  category: "main",
  filename: __filename
}, async (conn, mek, m, { q, reply, sender, pushname, from }) => {
  try {
    if (!q) {
      await sendFormattedMessage(
        conn, 
        from, 
        "🎨 *Please provide a prompt for the image*\n\n📌 *Usage:* .stabilityai cute cat\n🔍 *Example:* .stabilityai fantasy landscape", 
        sender, 
        pushname,
        "AI Image - Error",
        "No prompt"
      );
      return;
    }

    await sendFormattedMessage(
      conn, 
      from, 
      `🎨 *Creating your image with Stability AI...*\n\n📝 *Prompt:* ${q}\n⏳ Please wait!`, 
      sender, 
      pushname,
      "AI Image Generator",
      "Generating"
    );

    const apiUrl = `https://api.siputzx.my.id/api/ai/stabilityai?prompt=${encodeURIComponent(q)}`;
    const response = await axios.get(apiUrl, { responseType: "arraybuffer", timeout: 60000 });

    if (!response || !response.data) {
      await sendFormattedMessage(
        conn, 
        from, 
        "❌ *Error generating image*\n\nAPI did not return a valid image. Try again later.", 
        sender, 
        pushname,
        "AI Image - Error",
        "Generation failed"
      );
      return;
    }

    const imageBuffer = Buffer.from(response.data, "binary");

    await conn.sendMessage(from, {
      image: imageBuffer,
      caption: `🎨 *AI Generated Image*\n\n📝 *Prompt:* ${q}\n\n✨ *Generated by Stability AI*`
    }, { quoted: mek });

    await sendFormattedMessage(
      conn, 
      from, 
      `✅ *Image generated successfully!*\n\n📝 *Prompt:* ${q}\n\nEnjoy your AI artwork!`, 
      sender, 
      pushname,
      "AI Image - Success",
      "Image delivered"
    );

  } catch (error) {
    console.error("StabilityAI Error:", error);
    await sendFormattedMessage(
      conn, 
      from, 
      `❌ *An error occurred*\n\n${error.message || "Unknown error"}\n\nPlease try again later.`, 
      sender, 
      pushname,
      "AI Image - Error",
      "Generation failed"
    );
  }
});
